version: '3.7'
services:
  vscode:
    image: mwaeckerlin/vscode
    build: .
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: data
        target: /data
      - type: volume
        source: config
        target: /config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  data:
  config:
